/** 对象类型枚举 */
export enum TypeEnum {
  /** 基本数据类型 */
  /** 数字 */
  Number = 'Number',
  /** 字符串 */
  String = 'String',
  /** 布尔值 */
  Boolean = 'Boolean',
  /** Null */
  Null = 'Null',
  /** Undefined */
  Undefined = 'Undefined',
  /** Symbol */
  Symbol = 'Symbol',
  /** 大整数 */
  BigInt = 'BigInt',
  /** 对象数据类型 */
  /** 普通对象 */
  Object = 'Object',
  /** Arguments对象 */
  Arguments = 'Arguments',
  /** 数组 */
  Array = 'Array',
  /** 日期 */
  Date = 'Date',
  /** 正则 */
  RegExp = 'RegExp',
  /** Set */
  Set = 'Set',
  /** Map */
  Map = 'Map',
}
